services:
  queue:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes: 
      - db-ticket:/var/lib/postgresql/data 
  db-admin:
    image: dpage/pgadmin4:latest
    depends_on: 
      - db
    environment:
        PGADMIN_DEFAULT_EMAIL: user@localhost.com
        PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80
volumes:
  db-ticket:
    external: true